openapi: 3.0.1
info:
  title: AI DevOps Tools Integration API
  description: API contract for AI-enhanced DevOps tools integration in TodoFlow application
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /api/v1/ai-tools/kubectl-ai:
    post:
      summary: Execute kubectl-ai command
      description: Submit a natural language command to kubectl-ai for execution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KubectlAiRequest'
      responses:
        '200':
          description: Successful execution of kubectl-ai command
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KubectlAiResponse'
        '400':
          description: Invalid request or command
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/ai-tools/kagent:
    post:
      summary: Execute kagent cluster analysis
      description: Run AI-powered cluster analysis and diagnostics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KagentRequest'
      responses:
        '200':
          description: Successful cluster analysis
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KagentResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/ai-tools/gordon:
    post:
      summary: Generate Dockerfile with Gordon
      description: Use AI to generate a Dockerfile based on project requirements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GordonRequest'
      responses:
        '200':
          description: Dockerfile generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GordonResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    KubectlAiRequest:
      type: object
      properties:
        command:
          type: string
          description: Natural language command for kubectl-ai
          example: "scale frontend deployment to 3 replicas"
        namespace:
          type: string
          description: Kubernetes namespace (optional)
          example: "default"
        dry_run:
          type: boolean
          description: Whether to perform a dry run (default: false)
          example: false
      required:
        - command

    KubectlAiResponse:
      type: object
      properties:
        generated_command:
          type: string
          description: The kubectl command generated by AI
          example: "kubectl scale deployment frontend --replicas=3"
        yaml_output:
          type: string
          description: Generated YAML configuration (if applicable)
        execution_result:
          type: string
          description: Result of command execution
        ai_explanation:
          type: string
          description: Explanation of the AI's interpretation

    KagentRequest:
      type: object
      properties:
        analysis_type:
          type: string
          description: Type of analysis to perform
          enum: [health, resources, performance, security]
          example: "health"
        namespace_filter:
          type: string
          description: Filter analysis to specific namespace (optional)
          example: "todo-app"

    KagentResponse:
      type: object
      properties:
        analysis_report:
          type: string
          description: Comprehensive analysis report
        findings:
          type: array
          items:
            type: object
            properties:
              severity:
                type: string
                enum: [critical, high, medium, low]
              category:
                type: string
                example: "resource_allocation"
              description:
                type: string
                example: "Pod using 90% of allocated CPU limit"
              recommendation:
                type: string
                example: "Increase CPU limit or optimize application"
        summary:
          type: object
          properties:
            total_issues:
              type: integer
            critical_issues:
              type: integer
            duration_seconds:
              type: number

    GordonRequest:
      type: object
      properties:
        project_type:
          type: string
          description: Type of project to generate Dockerfile for
          enum: [nextjs, fastapi, react, express, flask]
          example: "nextjs"
        base_image_preference:
          type: string
          description: Preferred base image (optional)
          example: "node:20-alpine"
        security_requirements:
          type: array
          items:
            type: string
            enum: [non_root_user, minimal_base, multi_stage, scan_on_build]
          description: Security requirements for Dockerfile
        optimization_goals:
          type: array
          items:
            type: string
            enum: [smallest_size, fastest_build, best_security, best_performance]
          description: Optimization goals for Dockerfile
        project_path:
          type: string
          description: Path to project (optional, for analysis)
          example: "./frontend"

    GordonResponse:
      type: object
      properties:
        dockerfile_content:
          type: string
          description: Generated Dockerfile content
        validation_results:
          type: array
          items:
            type: object
            properties:
              rule:
                type: string
                description: Validation rule name
              status:
                type: string
                enum: [pass, warning, fail]
              message:
                type: string
                description: Validation message
        estimated_size_mb:
          type: number
          description: Estimated image size in MB
        build_time_estimate:
          type: string
          description: Estimated build time

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid command format"
        code:
          type: string
          description: Error code
          example: "INVALID_COMMAND"
        details:
          type: object
          description: Additional error details